project:
  type: website
  output-dir: docs

website:
  title: "Data Dispatches - JHU Data Services"
  reader-mode: false
  page-navigation: true
  search:
    location: sidebar
  
  navbar: 
    logo: logos/data-dispatches-white.png
    background: primary
    right: 
    - icon: github
      href: https://github.com/jhu-data-services
    - icon: globe 
      href: https://dataservices.library.jhu.edu/
    - text: "Help"
      menu:
        - text: "Report an Issue"
          icon: "bug"
          href: "https://github.com/jhu-data-services/data-dispatches/issues"
        - text: "Get Help"
          icon: "chat-right-text"
          href: "https://v2.libanswers.com/chati.php?hash=8b19eda5bc7bc7b80e623cad56abdd12"
        
  sidebar: 
    - id: dispatches
      title: "Data Tutorials"
      style: "floating"
      search: true
      collapse-level: 2
      contents:
        - index.qmd
       # - section: "Access and APIs"
       #   contents:
       #     - dispatches/data-access/index.qmd
       # - section: "Analysis"
       #   contents:
       #     - dispatches/data-analysis/index.qmd
        # - section: "Cleaning"
        #   contents:
        #     - dispatches/data-cleaning/index.qmd
        - section: "Data Visualization"
          contents:
            - dispatches/data-visualization/custom-ggplot2-theme.qmd
          
  page-footer: 
    background: primary
    left: "Copyright 2022, JHU Data Services." 
    right: "This site was built with [Quarto](https://quarto.org/)."
format:
  html:
    theme: litera 
    css: styles.css
    toc: true

editor: visual